name: 'Setup ROS2 environment'
description: 'Install ROS 2 from source on the host machine'
author: 'Thomas Moulard'
branding:
  icon: 'box'
  color: 'gray-dark'
runs:
  using: 'node12'
  main: 'lib/setup-ros2.js'
